name: Create Milestone

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "Set due_on"
        id: set-due-on
        run: |
            DUE_ON=$(date -u "+%Y-%m-%dT%H:%M:%SZ" -d "15 days")
            echo "due_on=$DUE_ON" >> $GITHUB_OUTPUT
            echo "title=$DUE_ON" >> $GITHUB_OUTPUT
            echo "description=$DUE_ON" >> $GITHUB_OUTPUT
        
      - name: "Print due_on"
        run: |
            echo "Due date is: ${{ steps.set-due-on.outputs.due_on }}"
            echo "Title is: ${{ steps.set-due-on.outputs.title }}"
            echo "Description is: ${{ steps.set-due-on.outputs.description }}"
            
      - name: "Create new milestone via GitHub API"
        shell: bash
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUBTOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/OWNER/REPO/milestones \
            -d '{"title":"v1.0","state":"open","description":"Tracking milestone for version 1.0","due_on":"2012-10-09T23:39:01Z"}'
        
#      - name: 'Create new milestone'
#        id: create-milestone
#        uses: kyoyadmoon/milestone-actions@v1.0.0
#        with:
#          title: "2.6.0"
#          state: "open"
#          description: "v2.6.0"
#          due_on: "${{ steps.set-due-on.outputs.due_on }}"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"

      - name: "Output created milestone number"
        run: echo ${{ steps.create-milestone.outputs.number }}
