name: Create Milestone

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create title, description and due-date
        id: init-value
        run: |
            DUE_ON=$(date -u "+%Y-%m-%dT%H:%M:%SZ" -d "15 days")
            echo "milestone_title=v1.0.1" >> $GITHUB_OUTPUT
            echo "due_on=$DUE_ON" >> $GITHUB_OUTPUT
      
#      - name: "Set due_on"
#        id: set-due-on
#        run: |
#            DUE_ON=$(date -u "+%Y-%m-%dT%H:%M:%SZ" -d "15 days")
#            DESCRIPTION=Tracking milestone for version 1.0
#            echo "due_on=$DUE_ON" >> $GITHUB_OUTPUT
#            echo "title=v1.0" >> $GITHUB_OUTPUT
#            echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
      - name: Create new milestone via GitHub API
        shell: bash
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUBTOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.OWNER_NAME }}/Bitrise-demo/milestones \
            -d '{"title":"${{ steps.init-value.outputs.milestone_title }}","state":"open","due_on":"${{ steps.init-value.outputs.due_on }}"}'
        
#      - name: 'Create new milestone'
#        id: create-milestone
#        uses: kyoyadmoon/milestone-actions@v1.0.0
#        with:
#          title: "2.6.0"
#          state: "open"
#          description: "v2.6.0"
#          due_on: "${{ steps.set-due-on.outputs.due_on }}"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"

      - name: Output created milestone number
        run: echo ${{ steps.create-milestone.outputs.number }}
