name: Create milestone

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
#      - name: Set title, description and due-date
#        id: init-value
#        run: |
#            DUE_ON=$(date -u "+%Y-%m-%dT%H:%M:%SZ" -d "14 days")
#            echo "milestone_title=v3.0.0" >> $GITHUB_OUTPUT
#            echo "due_on=$DUE_ON" >> $GITHUB_OUTPUT
      
      - name: Create new milestone via GitHub API
        id: create-milestone
        shell: bash
        run: |
          DUE_ON=$(date -u "+%Y-%m-%dT%H:%M:%SZ" -d "14 days")
          TITLE="MILESTONE_$(date -u "+%Y-%m-%d")"
          
          echo "Milestone title: $TITLE"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUBTOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ secrets.OWNER_NAME }}/Bitrise-demo/milestones \
            -d '{\"title\":\"$TITLE\",\"state\":\"open\",\"due_on\":\"$DUE_ON\"}'
