name: Create Milestone

on:
  push:
    branches:
      - main
      
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: set due_on
        id: set-due-on
        run: echo "due_on=$(date -d '13 days' '+%s')" >> $GITHUB_OUTPUT

      - name: 'Create new milestone'
        id: create-milestone
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: "1.7.0"
          description: "test desc"
          due_on: "${{ steps.set-due-on.outputs.due_on }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"

      - name: echo Milestone number
        run: echo ${{ steps.create-milestone.outputs.number }}

      - name: echo Milestone id
        run: echo ${{ steps.create-milestone.outputs.id }}

      - name: echo Milestone html_url
        run: echo ${{ steps.create-milestone.outputs.html_url }}
