name: Create Milestone

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: "Set due_on"
        id: set-due-on
        run: echo "due_on=$(date --iso-8601=seconds -d '13 days')" >> $GITHUB_OUTPUT

      - name: 'Create new milestone'
        id: create-milestone
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: "1.0.0"
          state: "open"
          description: "v1.0.0"
          due_on: "${{ steps.set-due-on.outputs.due_on }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Output created milestone number"
        run: echo ${{ steps.create-milestone.outputs.number }}
