name: Create Milestone

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: "Set due_on"
        id: set-due-on
        run: echo "DUE_ON=$(date --iso-8601=seconds -d '15 days')" >> $GITHUB_ENV
        
      - name: 'Create new milestone'
        id: create-milestone
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: "2.4.0"
          state: "open"
          description: "v2.4.0"
          due_on: "${{ env.DUE_ON }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUBTOKEN }}"

      - name: "Output created milestone number"
        run: echo ${{ steps.create-milestone.outputs.number }}
