name: Create Milestone

on:
  push:
    branches:
      - main

jobs:
  Create Milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: "Set due_on"
        id: set-due-on
        run: echo "DUE_ON=$(date --iso-8601=seconds -d '13 days')" >> $GITHUB_OUTPUT

      - name: "Create a new milestone"
        id: create-milestone
        uses: oinume/create-scheduled-milestone-action@v1
        with:
          title: "1.0.0"
          state: "open"
          description: "v1.0.0"
          due_on: "${{ env.DUE_ON }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Output created milestone number"
        run: echo ${{ steps.create-milestone.outputs.number }}
